apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app
        type: tier_1      
    spec:
      containers:
      - name: blub
        image: docker.io/khkrachenfels/game-of-life-conway-webserver
        ports:
        - containerPort: 5000